# Generated by Django 6.0.4 on 2026-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingArtifact',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=128)),
                ('kind', models.CharField(blank=True, default='', max_length=64)),
                ('path', models.TextField(blank=True, default='')),
                ('created_at', models.CharField(blank=True, default='', max_length=64)),
                ('promoted', models.BooleanField(default=False)),
                ('metrics', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingDataset',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(blank=True, default='', max_length=32)),
                ('local_path', models.TextField(blank=True, null=True)),
                ('archive_path', models.TextField(blank=True, null=True)),
                ('detected_format', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(default='ready', max_length=32)),
                ('sample_count', models.IntegerField(default=0)),
                ('class_count', models.IntegerField(default=0)),
                ('created_at', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'training_datasets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('dataset_id', models.CharField(db_index=True, max_length=128)),
                ('dataset_name', models.CharField(blank=True, max_length=255, null=True)),
                ('base_model', models.CharField(blank=True, default='', max_length=128)),
                ('task_type', models.CharField(blank=True, default='detect', max_length=32)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('progress', models.FloatField(default=0.0)),
                ('phase', models.CharField(blank=True, default='', max_length=128)),
                ('device', models.CharField(blank=True, default='cpu', max_length=32)),
                ('created_at', models.CharField(blank=True, default='', max_length=64)),
                ('started_at', models.CharField(blank=True, max_length=64, null=True)),
                ('finished_at', models.CharField(blank=True, max_length=64, null=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('params', models.JSONField(blank=True, null=True)),
                ('metrics', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('job_id', models.CharField(db_index=True, max_length=128)),
                ('ts', models.CharField(blank=True, default='', max_length=64)),
                ('level', models.CharField(blank=True, default='INFO', max_length=32)),
                ('message', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'training_logs',
                'ordering': ['ts'],
            },
        ),
    ]
