"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { API_BASE, alertImageUrl } from "@/lib/config";
import { Loader2, UploadCloud } from "lucide-react";
import { fetchHistory, type HistoryRow } from "@/lib/api";

type Job = {
  id: string;
  status: "queued" | "running" | "completed" | "failed";
  progress: number;
  message: string;
  createdAt: string;
  startedAt?: string | null;
  finishedAt?: string | null;
  alertsCreated: number;
};

export default function PlaybackPage() {
  const [file, setFile] = useState<File | null>(null);
  const [sampleFps, setSampleFps] = useState(2);
  const [maxSeconds, setMaxSeconds] = useState(0);
  const [busy, setBusy] = useState(false);
  const [msg, setMsg] = useState<string | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);

  // Temporary display of playback-related alerts right below the jobs cards.
  // These alerts are still persisted in the backend DB and remain visible in
  // the "History" tab.
  const [trackingJobId, setTrackingJobId] = useState<string | null>(null);
  const [playbackAlerts, setPlaybackAlerts] = useState<HistoryRow[]>([]);
  const clearTokenRef = useRef(0);

  const hasActive = useMemo(
    () => jobs.some((j) => j.status === "queued" || j.status === "running"),
    [jobs]
  );

  async function refresh(): Promise<Job[]> {
    try {
      const r = await fetch(`${API_BASE}/playback/jobs`, { cache: "no-store" });
      const j = await r.json();
      const next = Array.isArray(j) ? (j as Job[]) : [];
      setJobs(next);
      return next;
    } catch {
      // ignore
      return [];
    }
  }

  async function loadPlaybackAlerts(jobId: string) {
    try {
      const rows = await fetchHistory();

      // Backend alert image paths for playback look like:
      //   alerts/playback_<jobId>_<timestamp>.jpg
      const token = `playback_${jobId}_`;
      const filtered = rows.filter((row) => row.image_path.includes(token));
      setPlaybackAlerts(filtered);
    } catch {
      // ignore - keep last list
    }
  }

  async function refreshAll() {
    const nextJobs = await refresh();

    const nextActive = nextJobs.some(
      (j) => j.status === "queued" || j.status === "running"
    );

    // If nothing is active anymore, we assume "completed searches" and clear
    // the temporary alerts immediately.
    if (!nextActive) {
      clearTokenRef.current += 1;
      setPlaybackAlerts([]);
      setTrackingJobId(null);
      return;
    }

    if (!trackingJobId) return;

    const job = nextJobs.find((j) => j.id === trackingJobId);
    if (!job) {
      clearTokenRef.current += 1;
      setPlaybackAlerts([]);
      setTrackingJobId(null);
      return;
    }

    // If the tracked playback job already finished, clear immediately.
    if (job.status === "completed" || job.status === "failed") {
      clearTokenRef.current += 1;
      setPlaybackAlerts([]);
      setTrackingJobId(null);
      return;
    }

    // Otherwise keep the temporary alert log in sync.
    await loadPlaybackAlerts(trackingJobId);
  }

  useEffect(() => {
    refresh();
    const t = window.setInterval(() => {
      refresh();
    }, hasActive ? 1500 : 5000);
    return () => window.clearInterval(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [hasActive]);

  async function upload() {
    if (!file) {
      setMsg("Choose a video file first.");
      return;
    }
    setBusy(true);
    setMsg(null);
    try {
      const fd = new FormData();
      fd.append("file", file);
      fd.append("sampleFps", String(sampleFps));
      fd.append("maxSeconds", String(maxSeconds));

      const r = await fetch(`${API_BASE}/playback/upload`, {
        method: "POST",
        body: fd,
      });
      const j = await r.json();
      if (!r.ok) {
        setMsg(j?.detail ?? "Upload failed.");
      } else {
        setMsg(`Uploaded. Job: ${j.jobId}`);
        setTrackingJobId(j.jobId);
        setPlaybackAlerts([]);
        setFile(null);
        refresh();
      }
    } catch {
      setMsg("Network error.");
    } finally {
      setBusy(false);
    }
  }

  // Poll /history to get alerts generated by the currently uploaded playback job.
  useEffect(() => {
    if (!trackingJobId) return;

    let cancelled = false;
    const myClearToken = clearTokenRef.current;

    async function poll() {
      try {
        const rows = await fetchHistory();
        if (cancelled) return;
        // If we cleared logs (Refresh), ignore any in-flight results.
        if (myClearToken !== clearTokenRef.current) return;

        // Backend alert image paths for playback look like:
        //   alerts/playback_<jobId>_<timestamp>.jpg
        const token = `playback_${trackingJobId}_`;
        const filtered = rows.filter((row) =>
          row.image_path.includes(token)
        );
        setPlaybackAlerts(filtered);
      } catch {
        // ignore - keep last list
      }
    }

    poll();

    const interval = window.setInterval(poll, hasActive ? 1500 : 3000);
    return () => {
      cancelled = true;
      window.clearInterval(interval);
    };
  }, [trackingJobId, hasActive]);

  // Make the alert list temporary: clear it shortly after the tracked job ends.
  useEffect(() => {
    if (!trackingJobId) return;

    const job = jobs.find((j) => j.id === trackingJobId);
    if (!job) return;

    if (job.status !== "completed" && job.status !== "failed") return;

    const t = window.setTimeout(() => {
      clearTokenRef.current += 1;
      setPlaybackAlerts([]);
      setTrackingJobId(null);
    }, 30000);

    return () => window.clearTimeout(t);
  }, [jobs, trackingJobId]);

  return (
    <div className="mx-auto max-w-3xl space-y-8">
      <header>
        <h1 className="font-headline text-2xl font-semibold tracking-tight text-foreground">
          Playback testing
        </h1>
        <p className="mt-1 text-sm text-muted">
          Upload a recorded video to test detection on CPU without live RTSP
          lag. Alerts will appear in History.
        </p>
      </header>

      {msg && (
        <p className="rounded-fidelity border border-border bg-surface px-3 py-2 text-sm text-foreground">
          {msg}
        </p>
      )}

      <section className="space-y-4 rounded-fidelity border border-border bg-surface/70 p-4">
        <h2 className="text-sm font-medium text-foreground">Upload video</h2>

        <input
          type="file"
          accept="video/*"
          aria-label="Upload video file"
          className="block w-full text-sm text-muted file:mr-3 file:rounded-fidelity file:border-0 file:bg-neutral/20 file:px-3 file:py-2 file:text-foreground"
          onChange={(e) => setFile(e.target.files?.[0] ?? null)}
        />

        <div className="grid gap-3 sm:grid-cols-2">
          <label className="space-y-1">
            <span className="text-xs text-muted">Sample FPS (CPU load)</span>
            <input
              type="number"
              min={0.2}
              step={0.2}
              value={sampleFps}
              onChange={(e) => setSampleFps(Number(e.target.value))}
              className="w-full rounded-fidelity border border-border bg-background px-3 py-2 text-sm text-foreground"
            />
          </label>
          <label className="space-y-1">
            <span className="text-xs text-muted">
              Max seconds (0 = full video)
            </span>
            <input
              type="number"
              min={0}
              step={1}
              value={maxSeconds}
              onChange={(e) => setMaxSeconds(Number(e.target.value))}
              className="w-full rounded-fidelity border border-border bg-background px-3 py-2 text-sm text-foreground"
            />
          </label>
        </div>

        <button
          type="button"
          onClick={upload}
          disabled={busy}
          className="inline-flex items-center gap-2 rounded-fidelity bg-primary px-4 py-2 text-sm font-medium text-black hover:opacity-90 disabled:opacity-50"
        >
          {busy ? (
            <Loader2 className="h-4 w-4 animate-spin" />
          ) : (
            <UploadCloud className="h-4 w-4" />
          )}
          Upload & analyze
        </button>
      </section>

      <section className="space-y-3">
        <div className="flex items-center justify-between">
          <h2 className="text-sm font-medium uppercase tracking-wide text-muted">
            Jobs
          </h2>
          <button
            type="button"
              onClick={refreshAll}
            className="rounded-fidelity border border-border px-3 py-1.5 text-xs text-foreground hover:bg-neutral/15"
          >
            Refresh
          </button>
        </div>

        {jobs.length === 0 ? (
          <p className="text-sm text-muted">No jobs yet.</p>
        ) : (
          <ul className="space-y-2">
            {jobs.map((j) => (
              <li
                key={j.id}
                className="rounded-fidelity border border-border bg-surface/70 p-4"
              >
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <p className="font-mono text-xs text-muted">{j.id}</p>
                    <p className="mt-1 text-sm text-foreground">
                      {j.status.toUpperCase()} • {j.message}
                    </p>
                  </div>
                  <div className="text-right text-xs text-muted">
                    <div>Alerts: {j.alertsCreated}</div>
                    <div>{Math.round((j.progress ?? 0) * 100)}%</div>
                  </div>
                </div>
                <div className="mt-3 h-2 w-full overflow-hidden rounded-fidelity bg-neutral/20">
                  <div
                    className="progress-bar h-full bg-primary"
                    data-pct={Math.round((j.progress ?? 0) * 100)}
                  />
                </div>
              </li>
            ))}
          </ul>
        )}
      </section>

      {trackingJobId && (
        <section className="space-y-3 rounded-fidelity border border-border bg-surface/70 p-4">
          <div className="flex items-center justify-between">
            <h2 className="text-sm font-medium uppercase tracking-wide text-muted">
              Playback alerts (temporary)
            </h2>
            <span className="font-mono text-xs text-muted">
              {trackingJobId.slice(0, 8)}…
            </span>
          </div>

          {playbackAlerts.length === 0 ? (
            <p className="text-sm text-muted">
              No alerts yet. Running playback analysis…
            </p>
          ) : (
            <ul className="space-y-3">
              {playbackAlerts.map((a) => (
                <li
                  key={a.id}
                  className="flex flex-col gap-3 rounded-fidelity border border-border bg-surface/80 p-3 sm:flex-row sm:items-start"
                >
                  {/* eslint-disable-next-line @next/next/no-img-element */}
                  <img
                    src={alertImageUrl(a.image_path)}
                    alt=""
                    className="h-24 w-auto max-w-full rounded-fidelity border border-border object-cover"
                  />
                  <div className="min-w-0 flex-1">
                    <p className="text-sm font-semibold text-foreground">
                      {a.message}
                    </p>
                    <p className="mt-1 font-mono text-xs text-muted">
                      {a.timestamp}
                    </p>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </section>
      )}
    </div>
  );
}

